# This is a workflow to trigger the CI in alpa-projects/alpa.

name: Trigger Alpa CI to Build JAXlib and Alpa

on:
  workflow_dispatch:
    inputs:
      alpa:
        description: 'Alpa branch to test'
        required: true
        default: main

env:
  TF_BRANCH: ${{github.ref}}
  ALPA_BRANCH: ${{github.event.inputs.alpa}}

jobs:
  dispatch:
    if: github.repository == 'alpa-projects/tensorflow-alpa'  # Don't do this in forks
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Building with tensorflow-alpa/${TF_BRANCH##*/}"
          echo "Building with alpa/$ALPA_BRANCH"

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'alpa-projects',
              repo: 'alpa',
              workflow_id: 'build-jax.yml',
              ref: '${{github.event.inputs.alpa}}',
              inputs: {
                tensorflow: '${{github.ref}}'
              },
            })

